### PR TITLE
fix: automatically set attached mode for delve based on OS

### PR DESCRIPTION
**Pull request by PerMalmberg**
Hi,

Here's a change to automatically set the attached mode for delve so the end-user doesn't have to.

I added it to the config example too but maybe that entire line should be removed with this fix in place, let me know if I should do that.

Br,

### CODE REVIEW

**Comment by PerMalmberg** [comment]
@leoluz What is the actual issue referenced in the current code? For me it crashed if not setting this flag to false in Windows, but with dlv 1.22.1 this seems to no longer be true.

**Comment by PerMalmberg** [comment]
> @leoluz What is the actual issue referenced in the current code? For me it crashed if not setting this flag to false in Windows, but with dlv 1.22.1 this seems to no longer be true.

Scratch that, it still happens if not false. I must not have reloaded settings.

**Comment by PerMalmberg** [comment]
For other new NeoVim users like me, here's how you can set this value while maintaining the defaults. Just put this in a file on your plugins folder:

```lua
return {
	{
		"leoluz/nvim-dap-go",
		config = function(plugin, opts)
			opts.delve.detached = vim.fn.has("win32") == 0
		end,
	},
}
```

**Comment by gustavosinacio** [comment]
This fixes the config to work out of the box for different platforms. It seems to be the issue faced in this [stackoverflow post](https://stackoverflow.com/questions/78535636/error-debugging-go-code-with-neovim-and-nvim-dap-go-on-windows-dlv-exited-with/78660024#78660024). This probably should be merged.

**Review by leoluz — APPROVED** [review]
LGTM

**Pull request merged**
